// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilterExcelFile(arg1) {
  return window['go']['main']['App']['FilterExcelFile'](arg1);
}

export function GenerateActivityData(arg1) {
  return window['go']['main']['App']['GenerateActivityData'](arg1);
}

export function GetExcelFiles(arg1) {
  return window['go']['main']['App']['GetExcelFiles'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InterleaveTxtFiles(arg1) {
  return window['go']['main']['App']['InterleaveTxtFiles'](arg1);
}

export function MergeExcelFiles(arg1, arg2) {
  return window['go']['main']['App']['MergeExcelFiles'](arg1, arg2);
}

export function ProcessAgeColumn(arg1) {
  return window['go']['main']['App']['ProcessAgeColumn'](arg1);
}

export function ProcessTxtFiles(arg1) {
  return window['go']['main']['App']['ProcessTxtFiles'](arg1);
}

export function SelectExcelFiles() {
  return window['go']['main']['App']['SelectExcelFiles']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectSaveFile() {
  return window['go']['main']['App']['SelectSaveFile']();
}

export function SelectSaveTxtFile() {
  return window['go']['main']['App']['SelectSaveTxtFile']();
}

export function SelectTxtFile() {
  return window['go']['main']['App']['SelectTxtFile']();
}

export function SplitPhoneNumbers(arg1) {
  return window['go']['main']['App']['SplitPhoneNumbers'](arg1);
}

export function UpdateExcelFile(arg1) {
  return window['go']['main']['App']['UpdateExcelFile'](arg1);
}
