// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FilterExcelFile(arg1:main.FilterConfig):Promise<main.FilterResult>;

export function GenerateActivityData(arg1:main.ActivityConfig):Promise<main.ActivityResult>;

export function GetCountryList():Promise<Array<main.CountryOption>>;

export function GetExcelFiles(arg1:string):Promise<Array<string>>;

export function GetExcelHeaders(arg1:string):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function InterleaveTxtFiles(arg1:main.TxtInterleaveConfig):Promise<main.TxtInterleaveResult>;

export function MergeExcelFiles(arg1:Array<string>,arg2:main.MergeConfig):Promise<main.MergeResult>;

export function ProcessAgeColumn(arg1:main.AgeProcessConfig):Promise<main.AgeProcessResult>;

export function ProcessTxtFiles(arg1:main.TxtProcessConfig):Promise<main.TxtProcessResult>;

export function SelectExcelFile():Promise<string>;

export function SelectExcelFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function SelectSaveFile():Promise<string>;

export function SelectSaveTxtFile():Promise<string>;

export function SelectTxtFile():Promise<string>;

export function SplitByAreaCode(arg1:main.AreaCodeSplitConfig):Promise<main.AreaCodeSplitResult>;

export function SplitPhoneNumbers(arg1:main.PhoneSplitConfig):Promise<main.PhoneSplitResult>;

export function UpdateExcelFile(arg1:main.UpdateConfig):Promise<main.UpdateResult>;
